INSERT INTO Client (Name, CanProvideSecret, Active, RefreshTokenLifetime, AllowedOrigin)
VALUES ('Web App', 0, 1, 7200, '*')

INSERT INTO Activity (Name) VALUES('Aerobics')
INSERT INTO Activity (Name) VALUES('Aikido')
INSERT INTO Activity (Name) VALUES('American Football')
INSERT INTO Activity (Name) VALUES('Angling')
INSERT INTO Activity (Name) VALUES('Aquathon')
INSERT INTO Activity (Name) VALUES('Archery')
INSERT INTO Activity (Name) VALUES('Arm Wrestling')
INSERT INTO Activity (Name) VALUES('Athletics')
INSERT INTO Activity (Name) VALUES('Australian Rules Football')
INSERT INTO Activity (Name) VALUES('Baby Swimming')
INSERT INTO Activity (Name, IsDefault) VALUES('Badminton', 1)
INSERT INTO Activity (Name) VALUES('Ballooning')
INSERT INTO Activity (Name) VALUES('Ballroom Dancing')
INSERT INTO Activity (Name) VALUES('Baseball')
INSERT INTO Activity (Name, IsDefault) VALUES('Basketball', 1)
INSERT INTO Activity (Name) VALUES('Batton Twirling')
INSERT INTO Activity (Name) VALUES('Beach Volleyball')
INSERT INTO Activity (Name) VALUES('Biathlon')
INSERT INTO Activity (Name) VALUES('Bicycle Polo')
INSERT INTO Activity (Name) VALUES('Billiards')
INSERT INTO Activity (Name) VALUES('BMX')
INSERT INTO Activity (Name) VALUES('Boat Wakeboarding')
INSERT INTO Activity (Name) VALUES('Bobsleigh')
INSERT INTO Activity (Name) VALUES('Boccia')
INSERT INTO Activity (Name) VALUES('Boot Camp')
INSERT INTO Activity (Name) VALUES('Bowls')
INSERT INTO Activity (Name) VALUES('Boxercise')
INSERT INTO Activity (Name) VALUES('Boxing')
INSERT INTO Activity (Name) VALUES('British Military Fitness')
INSERT INTO Activity (Name) VALUES('Cable Wakeboarding')
INSERT INTO Activity (Name) VALUES('Camogie')
INSERT INTO Activity (Name) VALUES('Canoeing')
INSERT INTO Activity (Name) VALUES('Caving')
INSERT INTO Activity (Name) VALUES('Children''s outdoor gym')
INSERT INTO Activity (Name) VALUES('Circuits')
INSERT INTO Activity (Name) VALUES('Clay Pigeon Shooting')
INSERT INTO Activity (Name) VALUES('Climbing')
INSERT INTO Activity (Name) VALUES('Combat Class')
INSERT INTO Activity (Name, IsDefault) VALUES('Cricket', 1)
INSERT INTO Activity (Name) VALUES('Croquet')
INSERT INTO Activity (Name) VALUES('Cross Training/Crossfit')
INSERT INTO Activity (Name) VALUES('Curling')
INSERT INTO Activity (Name) VALUES('Cycle Speedway')
INSERT INTO Activity (Name) VALUES('Cycling')
INSERT INTO Activity (Name) VALUES('Darts')
INSERT INTO Activity (Name) VALUES('Disability Angling')
INSERT INTO Activity (Name) VALUES('Disability Archery')
INSERT INTO Activity (Name) VALUES('Disability Athletics')
INSERT INTO Activity (Name) VALUES('Disability Badminton')
INSERT INTO Activity (Name) VALUES('Disability Bowling')
INSERT INTO Activity (Name) VALUES('Disability Cricket')
INSERT INTO Activity (Name) VALUES('Disability Cycling')
INSERT INTO Activity (Name) VALUES('Disability Equestrian')
INSERT INTO Activity (Name) VALUES('Disability Football')
INSERT INTO Activity (Name) VALUES('Disability Golf')
INSERT INTO Activity (Name) VALUES('Disability Martial Arts')
INSERT INTO Activity (Name) VALUES('Disability Rambling')
INSERT INTO Activity (Name) VALUES('Disability Sailing')
INSERT INTO Activity (Name) VALUES('Disability Shooting')
INSERT INTO Activity (Name) VALUES('Disability Skiing')
INSERT INTO Activity (Name) VALUES('Disability Snooker')
INSERT INTO Activity (Name) VALUES('Disability Sports')
INSERT INTO Activity (Name) VALUES('Disability Surfing')
INSERT INTO Activity (Name) VALUES('Disability Swimming')
INSERT INTO Activity (Name) VALUES('Disability Table Tennis')
INSERT INTO Activity (Name) VALUES('Disability Trampolining')
INSERT INTO Activity (Name) VALUES('Disability Water Skiing')
INSERT INTO Activity (Name) VALUES('Disc Golf')
INSERT INTO Activity (Name) VALUES('Diving')
INSERT INTO Activity (Name) VALUES('Dodgeball')
INSERT INTO Activity (Name) VALUES('Dragon Boat Racing')
INSERT INTO Activity (Name) VALUES('Duathlon')
INSERT INTO Activity (Name) VALUES('Equestrian')
INSERT INTO Activity (Name) VALUES('Fencing')
INSERT INTO Activity (Name) VALUES('Fives')
INSERT INTO Activity (Name) VALUES('Floorball')
INSERT INTO Activity (Name) VALUES('Folk Dancing')
INSERT INTO Activity (Name, IsDefault) VALUES('Football', 1)
INSERT INTO Activity (Name) VALUES('Footgolf')
INSERT INTO Activity (Name) VALUES('Free Weights')
INSERT INTO Activity (Name) VALUES('Frisbee (ultimate)')
INSERT INTO Activity (Name) VALUES('Futsal')
INSERT INTO Activity (Name) VALUES('Gaelic Football')
INSERT INTO Activity (Name) VALUES('General Gym')
INSERT INTO Activity (Name) VALUES('Gliding')
INSERT INTO Activity (Name) VALUES('Goal Ball')
INSERT INTO Activity (Name) VALUES('Golf')
INSERT INTO Activity (Name) VALUES('Group Exercise Class')
INSERT INTO Activity (Name) VALUES('Gym Class Strength')
INSERT INTO Activity (Name) VALUES('Gym Class Toning')
INSERT INTO Activity (Name) VALUES('Gymnastics')
INSERT INTO Activity (Name) VALUES('Handball')
INSERT INTO Activity (Name) VALUES('Hang Gliding')
INSERT INTO Activity (Name) VALUES('Harness Racing')
INSERT INTO Activity (Name) VALUES('Health and Fitness')
INSERT INTO Activity (Name) VALUES('Highland Games')
INSERT INTO Activity (Name) VALUES('Hockey')
INSERT INTO Activity (Name) VALUES('Horse Racing')
INSERT INTO Activity (Name) VALUES('Horse Riding')
INSERT INTO Activity (Name) VALUES('Hovering')
INSERT INTO Activity (Name) VALUES('Hurling')
INSERT INTO Activity (Name) VALUES('Ice Hockey')
INSERT INTO Activity (Name) VALUES('Ice Skating')
INSERT INTO Activity (Name) VALUES('Indoor Climbing')
INSERT INTO Activity (Name) VALUES('Jet Skiing')
INSERT INTO Activity (Name) VALUES('Ju Jitsu')
INSERT INTO Activity (Name) VALUES('Judo')
INSERT INTO Activity (Name) VALUES('Kabaddi')
INSERT INTO Activity (Name) VALUES('Karate')
INSERT INTO Activity (Name) VALUES('Kayaking')
INSERT INTO Activity (Name) VALUES('Kendo')
INSERT INTO Activity (Name) VALUES('Kettlebell')
INSERT INTO Activity (Name) VALUES('Kickboxing')
INSERT INTO Activity (Name) VALUES('Kite Surfing')
INSERT INTO Activity (Name) VALUES('Knee Boarding')
INSERT INTO Activity (Name) VALUES('Korfball')
INSERT INTO Activity (Name) VALUES('Kung Fu')
INSERT INTO Activity (Name) VALUES('Lacrosse')
INSERT INTO Activity (Name) VALUES('Land Sailing')
INSERT INTO Activity (Name) VALUES('Martial Arts')
INSERT INTO Activity (Name) VALUES('Model Aircraft Flying')
INSERT INTO Activity (Name) VALUES('Modern Pentathlon')
INSERT INTO Activity (Name) VALUES('Motor Cruising')
INSERT INTO Activity (Name) VALUES('Motor Cycling')
INSERT INTO Activity (Name) VALUES('Motor Sports')
INSERT INTO Activity (Name) VALUES('Mountain Biking')
INSERT INTO Activity (Name) VALUES('Mountaineering')
INSERT INTO Activity (Name) VALUES('Movement & Dance')
INSERT INTO Activity (Name) VALUES('Netball')
INSERT INTO Activity (Name) VALUES('Ninjitsu')
INSERT INTO Activity (Name) VALUES('Nordic Walking')
INSERT INTO Activity (Name) VALUES('Octopush')
INSERT INTO Activity (Name) VALUES('Orienteering')
INSERT INTO Activity (Name) VALUES('Outdoor Climbing')
INSERT INTO Activity (Name) VALUES('Outdoor Gym')
INSERT INTO Activity (Name) VALUES('Park Fitness')
INSERT INTO Activity (Name) VALUES('Parkour')
INSERT INTO Activity (Name) VALUES('Petanque')
INSERT INTO Activity (Name) VALUES('Pilates')
INSERT INTO Activity (Name) VALUES('Polo')
INSERT INTO Activity (Name) VALUES('Polocrosse')
INSERT INTO Activity (Name) VALUES('Pool')
INSERT INTO Activity (Name) VALUES('Powerboating')
INSERT INTO Activity (Name) VALUES('Powerlifting')
INSERT INTO Activity (Name) VALUES('Powerplate')
INSERT INTO Activity (Name) VALUES('Quoits')
INSERT INTO Activity (Name) VALUES('Racketball')
INSERT INTO Activity (Name) VALUES('Rafting')
INSERT INTO Activity (Name) VALUES('Rambling')
INSERT INTO Activity (Name) VALUES('Real Tennis')
INSERT INTO Activity (Name) VALUES('Rhythmic Gymnastics')
INSERT INTO Activity (Name) VALUES('Road Cycling')
INSERT INTO Activity (Name) VALUES('Roller Hockey')
INSERT INTO Activity (Name) VALUES('Roller Speed Skating')
INSERT INTO Activity (Name) VALUES('Roller Sports')
INSERT INTO Activity (Name) VALUES('Rounders')
INSERT INTO Activity (Name) VALUES('Rowing')
INSERT INTO Activity (Name) VALUES('Rugby League')
INSERT INTO Activity (Name) VALUES('Rugby Union')
INSERT INTO Activity (Name) VALUES('Running')
INSERT INTO Activity (Name) VALUES('Sailing and Yachting')
INSERT INTO Activity (Name) VALUES('Scuba Diving')
INSERT INTO Activity (Name) VALUES('Shooting')
INSERT INTO Activity (Name) VALUES('Show Jumping')
INSERT INTO Activity (Name) VALUES('Sitting Volleyball')
INSERT INTO Activity (Name) VALUES('Skateboarding')
INSERT INTO Activity (Name) VALUES('Skiing')
INSERT INTO Activity (Name) VALUES('Skipping')
INSERT INTO Activity (Name) VALUES('Snooker')
INSERT INTO Activity (Name) VALUES('Snorkeling')
INSERT INTO Activity (Name) VALUES('Snowboarding')
INSERT INTO Activity (Name) VALUES('Softball')
INSERT INTO Activity (Name) VALUES('Sombo')
INSERT INTO Activity (Name) VALUES('Speedway')
INSERT INTO Activity (Name) VALUES('Spinning')
INSERT INTO Activity (Name, IsDefault) VALUES('Squash', 1)
INSERT INTO Activity (Name) VALUES('Stoolball')
INSERT INTO Activity (Name) VALUES('Street Hockey')
INSERT INTO Activity (Name) VALUES('Sub Aqua')
INSERT INTO Activity (Name) VALUES('Surf Life Saving')
INSERT INTO Activity (Name) VALUES('Surfing')
INSERT INTO Activity (Name) VALUES('Swimming')
INSERT INTO Activity (Name) VALUES('Synchronised Swimming')
INSERT INTO Activity (Name) VALUES('Table Tennis')
INSERT INTO Activity (Name) VALUES('Taekwondo')
INSERT INTO Activity (Name) VALUES('Tai Chi')
INSERT INTO Activity (Name) VALUES('Tang Soo Do')
INSERT INTO Activity (Name, IsDefault) VALUES('Tennis', 1)
INSERT INTO Activity (Name) VALUES('Tenpin Bowling')
INSERT INTO Activity (Name) VALUES('Track Cycling')
INSERT INTO Activity (Name) VALUES('Trail Running')
INSERT INTO Activity (Name) VALUES('Trampolining')
INSERT INTO Activity (Name) VALUES('Triathlon')
INSERT INTO Activity (Name) VALUES('Tug of War')
INSERT INTO Activity (Name) VALUES('Virtual Trainer/fitness')
INSERT INTO Activity (Name) VALUES('Volleyball')
INSERT INTO Activity (Name) VALUES('Wakeboarding')
INSERT INTO Activity (Name) VALUES('Walking')
INSERT INTO Activity (Name) VALUES('Water Polo')
INSERT INTO Activity (Name) VALUES('Water Skiing')
INSERT INTO Activity (Name) VALUES('Weightlifting')
INSERT INTO Activity (Name) VALUES('Wheelchair Basketball')
INSERT INTO Activity (Name) VALUES('Wheelchair Cardio')
INSERT INTO Activity (Name) VALUES('Wheelchair Fencing')
INSERT INTO Activity (Name) VALUES('Wheelchair Rugby')
INSERT INTO Activity (Name) VALUES('Wheelchair Tennis')
INSERT INTO Activity (Name) VALUES('Windsurfing')
INSERT INTO Activity (Name) VALUES('Wrestling')
INSERT INTO Activity (Name) VALUES('Yoga')
INSERT INTO Activity (Name) VALUES('Zumba')
